baseURL = 'https://lxz-bjut.github.io/'
title = '李博的学术主页'

defaultContentLanguage = 'zh'
enableGitInfo = true
disableKinds = ["taxonomy", "term", "RSS"]

[module]
  [[module.imports]]
    path = 'github.com/geekifan/zero-academic-page'

[languages]
  [languages.zh]
    languageName = '中文'
    weight = 1
    title = '李博的学术主页'

    [languages.zh.params]
      author = "李博"
      description = "土木工程博士生，研究桥墩冲刷与 OpenFOAM 多相耦合建模"
      motto = "以科学之眼解析水沙之道"

    [[languages.zh.menu.main]]
      name = '关于我'
      url = '#about-me'
      weight = 1
    [[languages.zh.menu.main]]
      name = '研究成果'
      url = '#publications'
      weight = 2
    [[languages.zh.menu.main]]
      name = '简历'
      url = '#cv'
      weight = 3
